/**
 * MemoryStore is a lightweight ref registry that lives on the main thread.
 *
 * It tracks **which memory refs exist** (and optional metadata) but does NOT
 * store actual data. All large datasets are held inside the dedicated
 * `MemoryWorker` thread, keeping the main thread heap free.
 *
 * Each ref is indexed by a cryptographically generated UUID to ensure
 * collision-free, secure handle management.
 */
export class MemoryStore {
  private readonly store = new Map<string, RefMetadata>();

  /**
   * Registers a ref in the registry.
   *
   * @param ref - The memory reference ID (generated by MemoryWorkerProxy).
   * @param metadata - Optional metadata (size hint, type tag, etc.).
   */
  register(ref: string, metadata: RefMetadata = {}): void {
    this.store.set(ref, metadata);
  }

  /**
   * Checks if a reference ID is registered.
   * @param refId - The reference ID to check.
   */
  has(refId: string): boolean {
    return this.store.has(refId);
  }

  /**
   * Unregisters a reference ID.
   *
   * @param refId - The reference ID to unregister.
   * @returns `true` if the key existed and was removed, `false` otherwise.
   */
  delete(refId: string): boolean {
    return this.store.delete(refId);
  }

  /**
   * Clears all registered references.
   */
  clear(): void {
    this.store.clear();
  }

  /**
   * Returns statistics about current registered handles.
   */
  stats(): { count: number; refs: string[] } {
    return {
      count: this.store.size,
      refs: Array.from(this.store.keys()),
    };
  }
}

/** Lightweight metadata stored alongside a ref in the main-thread registry. */
export interface RefMetadata {
  /** Optional size hint in bytes for diagnostics. */
  size?: number;
  /** Optional type tag (e.g. 'array', 'object'). */
  type?: string;
}
