import { WorkerFunction } from '../main-worker-factory/types';

/**
 * Generates the source code for an inline worker script that wraps a
 * serialised user function.
 *
 * The generated script:
 * 1. Embeds a self-contained copy of `extractTransferables` so transferable
 *    objects in the return value are moved (not cloned) back to the main thread.
 * 2. Listens for a single `message` event, calls the user function with the
 *    event data, and posts back `{ ok: true, data }` on success or
 *    `{ ok: false, error }` on failure.
 *
 * @param func - The stringified worker function (via `.toString()`).
 * @returns A self-contained JavaScript string ready to be turned into a
 *   `Blob` worker.
 */
const workerTemplate = (func: string) => `
const extractTransferables = (value, seen = new Set()) => {
  if (value === null || typeof value !== 'object') return [];
  if (seen.has(value)) return [];
  seen.add(value);
  if (value instanceof ArrayBuffer || value instanceof MessagePort ||
      (typeof ImageBitmap !== 'undefined' && value instanceof ImageBitmap) ||
      (typeof OffscreenCanvas !== 'undefined' && value instanceof OffscreenCanvas)) {
    return [value];
  }
  if (ArrayBuffer.isView(value)) return [value.buffer];
  if (Array.isArray(value)) return value.flatMap(i => extractTransferables(i, seen));
  return Object.values(value).flatMap(v => extractTransferables(v, seen));
};

self.addEventListener('message', async (event) => {
  try {
    const output = await ${func}(event.data);
    self.postMessage({ ok: true, data: output }, extractTransferables(output));
  } catch (err) {
    self.postMessage({ ok: false, error: err instanceof Error ? err.message : String(err) });
  }
})
`;

/**
 * Generates a pipeline-aware worker script.
 *
 * This worker can:
 * - Receive pipeline port configuration via a `__pipeline_ports__` message
 * - Listen for input on an `inputPort` (from previous worker) or via `self`
 * - Forward output to an `outputPort` (to next worker) or back to main thread
 *
 * @param func - The stringified worker function (via `.toString()`).
 */
const pipelineWorkerTemplate = (func: string) => `
const extractTransferables = (value, seen = new Set()) => {
  if (value === null || typeof value !== 'object') return [];
  if (seen.has(value)) return [];
  seen.add(value);
  if (value instanceof ArrayBuffer || value instanceof MessagePort ||
      (typeof ImageBitmap !== 'undefined' && value instanceof ImageBitmap) ||
      (typeof OffscreenCanvas !== 'undefined' && value instanceof OffscreenCanvas)) {
    return [value];
  }
  if (ArrayBuffer.isView(value)) return [value.buffer];
  if (Array.isArray(value)) return value.flatMap(i => extractTransferables(i, seen));
  return Object.values(value).flatMap(v => extractTransferables(v, seen));
};

const workerFn = ${func};
let outputPort = null;
let inputPort = null;
let pendingData = null;

async function processData(data) {
  try {
    const output = await workerFn(data);
    const result = { ok: true, data: output };
    const transfers = extractTransferables(output);
    if (outputPort) {
      outputPort.postMessage(result, transfers);
    } else {
      self.postMessage(result, transfers);
    }
  } catch (err) {
    const result = { ok: false, error: err instanceof Error ? err.message : String(err) };
    if (outputPort) {
      outputPort.postMessage(result);
    } else {
      self.postMessage(result);
    }
  }
}

self.addEventListener('message', (event) => {
  if (event.data && event.data.__pipeline_ports__) {
    if (event.data.outputPort) {
      outputPort = event.data.outputPort;
    }
    if (event.data.inputPort) {
      inputPort = event.data.inputPort;
      inputPort.onmessage = (e) => {
        if (e.data && e.data.ok === false) {
          // Propagate errors through the pipeline
          if (outputPort) outputPort.postMessage(e.data);
          else self.postMessage(e.data);
        } else {
          processData({ data: e.data.data, index: 0 });
        }
      };
    }
    // If we already received data before ports, process it now
    if (pendingData !== null) {
      processData(pendingData);
      pendingData = null;
    }
    return;
  }
  // First worker in pipeline or standalone — process directly
  if (!inputPort) {
    processData(event.data);
  } else {
    // Store data until ports are configured
    pendingData = event.data;
  }
});
`;

export interface WorkerFactoryOptions {
  /** When true, generates a pipeline-aware worker that supports MessagePort forwarding */
  pipeline?: boolean;
}

/**
 * Low-level factory that serialises a {@link WorkerFunction} into a Blob URL
 * and spawns a native `Worker` from it.
 *
 * `WorkerFactory` is an internal building block used by `MainWorkerFactory`.
 * It handles the mechanics of turning a plain TypeScript function into a
 * runnable worker thread — you rarely need to use it directly.
 *
 * The worker script is generated by {@link workerTemplate}, which wraps the
 * function with a message listener and transferable-extraction logic.
 */
class WorkerFactory {
  readonly _worker: Worker;

  /**
   * Creates a new `Worker` from the given function.
   *
   * The function is stringified, embedded into a self-contained worker script,
   * converted to a `Blob` URL, and passed to the `Worker` constructor.
   *
   * @param workerFunction - The function to run inside the worker thread.
   *   Must be self-contained — it cannot reference variables from the outer
   *   scope because it is serialised via `.toString()`.
   * @param options - Optional configuration. Set `pipeline: true` for
   *   pipeline-aware workers that support MessagePort forwarding.
   */
  constructor(workerFunction: WorkerFunction, options?: WorkerFactoryOptions) {
    const template = options?.pipeline
      ? pipelineWorkerTemplate
      : workerTemplate;
    const workerCode: string = template(workerFunction.toString());
    const workerBlob = new Blob([workerCode], {
      type: 'application/javascript',
    });

    this._worker = new Worker(URL.createObjectURL(workerBlob));
  }

  /**
   * Returns the underlying native `Worker` instance.
   *
   * Use this to attach `onmessage` / `onerror` handlers and call
   * `postMessage` / `terminate` directly.
   */
  get getWorker() {
    return this._worker;
  }
}

export default WorkerFactory;
