import { WorkerFunction } from '../main-worker-factory/types';

/**
 * Generates the source code for an inline worker script that wraps a
 * serialised user function.
 *
 * The generated script:
 * 1. Embeds a self-contained copy of `extractTransferables` so transferable
 *    objects in the return value are moved (not cloned) back to the main thread.
 * 2. Listens for a single `message` event, calls the user function with the
 *    event data, and posts back `{ ok: true, data }` on success or
 *    `{ ok: false, error }` on failure.
 *
 * @param func - The stringified worker function (via `.toString()`).
 * @returns A self-contained JavaScript string ready to be turned into a
 *   `Blob` worker.
 */
const workerTemplate = (func: string) => `
const extractTransferables = (value, seen = new Set()) => {
  if (value === null || typeof value !== 'object') return [];
  if (seen.has(value)) return [];
  seen.add(value);
  if (value instanceof ArrayBuffer || value instanceof MessagePort ||
      (typeof ImageBitmap !== 'undefined' && value instanceof ImageBitmap) ||
      (typeof OffscreenCanvas !== 'undefined' && value instanceof OffscreenCanvas)) {
    return [value];
  }
  if (ArrayBuffer.isView(value)) return [value.buffer];
  if (Array.isArray(value)) return value.flatMap(i => extractTransferables(i, seen));
  return Object.values(value).flatMap(v => extractTransferables(v, seen));
};

self.addEventListener('message', async (event) => {
  try {
    const output = await ${func}(event.data);
    self.postMessage({ ok: true, data: output }, extractTransferables(output));
  } catch (err) {
    self.postMessage({ ok: false, error: err instanceof Error ? err.message : String(err) });
  }
})
`;

/**
 * Low-level factory that serialises a {@link WorkerFunction} into a Blob URL
 * and spawns a native `Worker` from it.
 *
 * `WorkerFactory` is an internal building block used by `MainWorkerFactory`.
 * It handles the mechanics of turning a plain TypeScript function into a
 * runnable worker thread — you rarely need to use it directly.
 *
 * The worker script is generated by {@link workerTemplate}, which wraps the
 * function with a message listener and transferable-extraction logic.
 */
class WorkerFactory {
  readonly _worker: Worker;

  /**
   * Creates a new `Worker` from the given function.
   *
   * The function is stringified, embedded into a self-contained worker script,
   * converted to a `Blob` URL, and passed to the `Worker` constructor.
   *
   * @param workerFunction - The function to run inside the worker thread.
   *   Must be self-contained — it cannot reference variables from the outer
   *   scope because it is serialised via `.toString()`.
   */
  constructor(workerFunction: WorkerFunction) {
    const workerCode: string = workerTemplate(workerFunction.toString());
    const workerBlob = new Blob([workerCode], {
      type: 'application/javascript',
    });

    this._worker = new Worker(URL.createObjectURL(workerBlob));
  }

  /**
   * Returns the underlying native `Worker` instance.
   *
   * Use this to attach `onmessage` / `onerror` handlers and call
   * `postMessage` / `terminate` directly.
   */
  get getWorker() {
    return this._worker;
  }
}

export default WorkerFactory;
