name: Publish to NPM

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build:lib

      - name: Publish to NPM
        run: npm publish --access public --provenance

      - name: Upload npm debug log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-log
          path: /home/runner/.npm/_logs/
